name: actions-test
author: aftertale
description: just a test
inputs:
  gh_token:
    required: true
    description: "GitHub Token"
  prefix:
    required: false
    description: "An optional tag prefix, useful for repositories that have multiple tools or services."
outputs:
  envs:
    description: "All the environment vars"
  payload:
    description: "The context of the event that triggered the workflow"
runs:
  using: 'node16'
  main: 'main.js'


