name: Publish
on:
  push:
    branches:
      - 'main'

jobs:
  get_previous_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: AutoIncrement Version
        id: version
        run: |
          echo "::set-output name=new_tag::$(./.github/scripts/nextversion.sh)"

      - name: Tag with new version
        run: |
          git tag -a "v${{ steps.version.new_tag }}" -m "v${{ steps.version.new_tag }}"
          git push origin "v${{ steps.version.new_tag }}"
