name: Publish
on:
  push:
    branches:
      - 'main'

jobs:
  autoincrement_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: AutoIncrement Version
        id: version
        run: |
          git config --global user.email "djmcdowell81@gmail.com"
          git config --global user.name "Dillon McDowell"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          rev=$(git rev-list --tags --max-count=1)
          tag=$(git describe --tags "$rev" | sed 's/v//g')
          new_version_w_changes=($(./.github/scripts/nextversion.sh $tag))
          echo "::set-output name=chglevel::${new_version_with_changes[0]}"
          echo "::set-output name=new_tag::${new_version_with_changes[1]}"
      - name: Tag with new version
        run: |
          tag=${{ steps.version.outputs.new_tag }}
          tagArr=(${tag//./ })
          if [ ${{ steps.version.outputs.chglevel }} = 3 ]
          then
            git tag -a "v${tagArr[0]}" -m "v${tagArr[0]}"
            git tag -a "v${tagArr[0]}.${tagArr[1]}" -m "v${tagArr[0]}.${tagArr[1]}"
          elif [ ${{ steps.version.outputs.chglevel }} = 2 ]
          then
            
          fi

          git tag -a "v$tag" -m "v$tag"

