name: Publish
on:
  push:
    branches:
      - 'main'

jobs:
  autoincrement_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: AutoIncrement Version
        id: version
        run: |
          git config --global user.email "djmcdowell81@gmail.com"
          git config --global user.name "Dillon McDowell"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          rev=$(git rev-list --tags --max-count=1)
          tag=$(git describe --tags "$rev" | sed 's/v//g')
          new_tag=($(./.github/scripts/nextversion.sh $tag))

          git tag -fa "v${new_tag[0]}" -m "v${new_tag[1]}"
          git tag -fa "v${new_tag[0]}.${new_tag[1]}" -m "v${new_tag[0]}.${new_tag[1]}"
          git tag -fa "v${new_tag[0]}.${new_tag[1]}.${new_tag[2]}" -m "v${new_tag[0]}.${new_tag[1]}.${new_tag[2]}"
          git push -f --tags
