name: Publish
on:
  push:
    branches:
      - 'main'

jobs:
  get_previous_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get version
        id: old_version
        run: |
          echo "::set-output name=old_version::$(git describe)"
      - name: get changes
        run: |

