name: Publish
on:
  push:
    branches:
      - 'main'

jobs:
  autoincrement_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: AutoIncrement Version
        id: version
        run: |
          git config --global user.email "djmcdowell81@gmail.com"
          git config --global user.name "Dillon McDowell"
          tag=$(git tag 2>/dev/null | tail -n 1)
          echo "$tag"
          echo "::set-output name=new_tag::$(./.github/scripts/nextversion.sh)"

      - name: Tag with new version

        run: |
          git tag -a "v${{ steps.version.outputs.new_tag }}" -m "v${{ steps.version.outputs.new_tag }}"
          git push origin "v${{ steps.version.outputs.new_tag }}"
